language: java
jdk:
  - oraclejdk8
before_install:
  - chmod +x mvnw
script: "mvn verify -Dgpg.skip=true -Dmaven.javadoc.skip=$(echo $TRAVIS_JDK_VERSION | grep -q openjdk6 && echo -n true || echo -n false) -B -q"
